### ISSUE TITLE
if printing from SD fails, heaters will stay on.

### ISSUE THREAD

**Issue by AndKe** [ErikZalm/Marlin#1036] opened 2014-08-15 19:09 UTC
I've found some "bad" SD cards, that have a tendency to stop the printer somehow while printing.
reformatting does not help, fsck does not see problem, and file checksum is ok.

Anyway - when this happens, the printing stops, but both heaters remain on.
There should be a failsafe, if no activity while printing from SDcard - then turn off heaters.

**Comment by gregrebholz** [comment] 2015-01-02 16:09
As @whosawhatsis said above, this watchdog timeout feature is already implemented as "M85 S60" in your start-gcode if you want to kill() Marlin after 60 seconds of no new code arriving.  (You'll need M85 S0 in your end-gcode so you can idle without requiring a board reset to start a new print)  The issue of the same timer being reused in the runout prevention appears to have been addressed in commit b1f8f492c6908c62604833c4062e101f2490ebd6 but then reverted in f08bb8bb6a587b326222af9b678dae3922619493 as "borked"... It sounds like this issue is really "fix M85 conflict with runout prevention timer".

**Comment by boelle** [comment] 2015-01-02 16:12
is other people can confirm that i can rename the title to match... but dinner is up so it will be in 1-2 hours

**Comment by boelle** [comment] 2015-01-02 19:02
back... should i just rename this one?

**Comment by alexborro** [comment] 2015-01-02 19:14
I think this protections is already performed by M85 as well.. I don't
think it is worth a new development..

Cheers..

Alex.

2015-01-02 17:02 GMT-02:00 Bo Herrmannsen <notifications@github.com>:

> back... should i just rename this one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ErikZalm/Marlin/issues/1036#issuecomment-68552143>.
>



-- 
*"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )*

Alex Borro

**Comment by boelle** [comment] 2015-01-02 19:15
ok, will close this one then... we can always reopen if a very good argument is given along with a clean example

**Closed by boelle** 2015-01-02 19:15 UTC
Labels: Verified bug

**Comment by Silly105** [comment] 2015-01-02 19:37
Well... okay. That was much less work than i thought. :)
But if i get @gregrebholz right, the timer conflict is still in the code.

**Comment by boelle** [comment] 2015-01-02 19:39
maybe test the latest dev and see if the problem is there?

**Comment by AndKe** [comment] 2015-01-02 20:15
agree, as long M85 works as expected, that's the correct solution.

**Comment by gregrebholz** [comment] 2015-01-03 02:19
That's how I read the change log and a quick look over the code, but I haven't tested it myself.  Both runout prevention and M85 use the same variable (previous_millis_cmd) to track the passage of time since new commands, and both features reset it to "now" when they've done something - so enabling "runout prevention" (on an otherwise idle machine with the extruder heater active, a little filament is extruded periodically to prevent clogs) makes the M85 watchdog unable to detect when the host has stopped sending new gcode.  

If someone is volunteering to test I would recommend doing it first without runout prevention (the default) to confirm your testing methodology triggers the M85 watchdog.  Things like Octoprint are silently sending gcode to get status updates for the UI which will probably prevent it from triggering; and then recompile with EXTRUDER_RUNOUT_PREVENT defined in Configuration_adv.h to test if this condition still exists.
